const form = {
  id: '86c45bc2-e9ea-4481-afef-34f2f9b4431e',
  name: 'Reserve',
  reference: 'reserve',
  category: 'checklist',
  endpoint: 'd/inspection',
  multi: 1,
  props: { questionWidth: 12, answerWidth: 12, required: true },
  questions: [
    {
      component: 'SetTitle',
      props: {
        form_id: '{form_id}',
        asset_id: '{parent_id}',
        // text: 'on {date::inspection_date}',
      },
    },
    {
      text: 'Inspection date',
      reference: 'inspection_date',
      component: 'Date',
      form_props: { questionWidth: 2, answerWidth: 10 },
    },
    {
      id: 'c7e5969b-477f-4d2d-b81e-da2ec2ebd3ab',
      props: { text: 'Car Parking, Vehicle & Pedestrian Access' },
      component: 'FormSection',
    },
    {
      parent_id: 'c7e5969b-477f-4d2d-b81e-da2ec2ebd3ab',
      text: 'Are all fences, bollards and gates in good order to protect assets and restrict access?',
      reference: 'car-park-fences',
      component: 'Compliance',
    },
    {
      parent_id: 'c7e5969b-477f-4d2d-b81e-da2ec2ebd3ab',
      text: 'Is the car park linemarking and signage easy to see?',
      reference: 'car-park-linemarking',
      component: 'Compliance',
    },
    {
      parent_id: 'c7e5969b-477f-4d2d-b81e-da2ec2ebd3ab',
      text: 'Is the carpark, roadways and footpaths have any trip hazards or pot holes and free from debris?',
      reference: 'car-park-debris',
      component: 'Compliance',
    },
    {
      parent_id: 'c7e5969b-477f-4d2d-b81e-da2ec2ebd3ab',
      text: 'Is designated disabled access provided adequately?',
      reference: 'car-park-disabled-access',
      component: 'Compliance',
    },
    {
      id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      component: 'FormSection',
      props: { text: 'Playing Surface and Surrounds' },
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is the playing surface level, have adequate cover, no holes or cracking? Estimate grass cover %',
      reference: 'playing-surface-level',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is the scoring apparatus (goal posts/nets/rings/boards) in good condition and free of damage/rust?',
      reference: 'scoring-apparatus',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is the ground run offs compliant with the standards respective of the sport played?',
      reference: 'ground-run-offs',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is the playing surface appropriately line marked being compliant with standards respective of the sport played? Dimensions?',
      reference: 'playing-surface-line-marking',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is the oval boundary fence, advertising, benches and coaches boxes in good condition and safely presented?',
      reference: 'oval-boundary-fence',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is there any risks associated with the ground/playing surface e.g hardness, pit covers, weeds, stones, glass, drainage concerns?',
      reference: 'playing-surface-risk',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is the irrigation and lighting fixtures in good condition e.g damage to sprinkler heads?',
      reference: 'irrigation-lighting',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is there any risks posed by infrastructure located close by e.g roads, footpaths, adjacent property, spectators, car parks, playgrounds, slope?',
      reference: 'infrastructure-risks',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is there any issue with location of trees (near courts, pathways, car parks, sports grounds)?',
      reference: 'location-trees',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is any vehicle impacts or machinery maintenance required?',
      reference: 'vehicle-impacts',
      component: 'Compliance',
    },
    {
      parent_id: '88e5db04-dcab-43ee-85c3-64f6449ec9c6',
      text: 'Is the access gate, onto the oval, padlocked and appropriately signed for emergency vehicles?',
      reference: 'access-gate',
      component: 'Compliance',
    },
    {
      id: '4db38a6e-4fe6-4bf2-b8c2-536ae1acab22',
      props: { text: 'Cricket Practice Nets and Surrounds' },
      component: 'FormSection',
    },
    {
      parent_id: '4db38a6e-4fe6-4bf2-b8c2-536ae1acab22',
      text: 'Is the condition of the cricket wicket surface adequate e.g concrete cracks, torn, lifting or work carpet overlay?',
      reference: 'cricket-wicket-surface-condition',
      component: 'Compliance',
    },
    {
      parent_id: '4db38a6e-4fe6-4bf2-b8c2-536ae1acab22',
      text: 'Is there any proximity or orientation risks with the cricket nets?',
      reference: 'cricket-nets-risks',
      component: 'Compliance',
    },
    {
      parent_id: '4db38a6e-4fe6-4bf2-b8c2-536ae1acab22',
      text: 'Is the condition of the cricket run ups adequate e.g level?',
      reference: 'cricket-run-ups',
      component: 'Compliance',
    },
    {
      parent_id: '4db38a6e-4fe6-4bf2-b8c2-536ae1acab22',
      text: 'Is the condition of the cricket netting suitable, free of holes?',
      reference: 'cricket-netting-suitable',
      component: 'Compliance',
    },
    {
      parent_id: 'f5e0f700-7952-42e8-998f-7b1015cee5f5',
      props: { text: 'Oval Change Rooms' },
      component: 'FormSection',
    },
    {
      parent_id: 'f5e0f700-7952-42e8-998f-7b1015cee5f5',
      text: 'Is there any fire or arson risks (unrestrained wheelie bins, skip bins, combustible or hazardous materials, electrical or gas issues, access to underside of building)?',
      reference: 'oval-change-rooms-risks',
      component: 'Compliance',
    },
    {
      parent_id: 'f5e0f700-7952-42e8-998f-7b1015cee5f5',
      text: 'Is security measures adequate (fencing, lighting, accessible skylights, visible portable equipment, vandalism)?',
      reference: 'oval-change-rooms-security',
      component: 'Compliance',
    },
    {
      parent_id: 'f5e0f700-7952-42e8-998f-7b1015cee5f5',
      text: 'Are both change room areas and amenities clean, neat and tidy and free of rubbish?',
      reference: 'oval-change-rooms-amenities',
      component: 'Compliance',
    },
    {
      parent_id: 'f5e0f700-7952-42e8-998f-7b1015cee5f5',
      text: 'Is there any obvious property defects/hazards (slip or trip hazards, cracking, severe corrosion, breaks)?',
      reference: 'oval-change-rooms-defects',
      component: 'Compliance',
    },
    {
      parent_id: 'f5e0f700-7952-42e8-998f-7b1015cee5f5',
      text: 'Is there any issues with water/stormwater systems (Hot water systems, blocked drains/gutters, poor plumbing maintenance, overhanging trees)?',
      reference: 'oval-change-rooms-water-systems',
      component: 'Compliance',
    },
    {
      id: '8b9c224c-7860-4df6-9d52-6a28e885b78d',
      props: { text: 'Netball Pavilion Change Rooms' },
      component: 'FormSection',
    },
    {
      parent_id: '8b9c224c-7860-4df6-9d52-6a28e885b78d',
      text: 'Is there any obvious property defects/hazards (slip or trip hazards, cracking, severe corrosion, breaks)?',
      reference: 'netball-change-rooms-defects',
      component: 'Compliance',
    },
    {
      parent_id: '8b9c224c-7860-4df6-9d52-6a28e885b78d',
      text: 'Are both change room areas and amenities clean, neat and tidy and free of rubbish?',
      reference: 'netball-change-rooms-amenities',
      component: 'Compliance',
    },
    {
      parent_id: '8b9c224c-7860-4df6-9d52-6a28e885b78d',
      text: 'Is security measures adequate (fencing, lighting, accessible skylights, visible portable equipment, vandalism)?',
      reference: 'netball-change-rooms-security',
      component: 'Compliance',
    },
    {
      parent_id: '8b9c224c-7860-4df6-9d52-6a28e885b78d',
      text: 'Is there any fire or arson risks (unrestrained wheelie bins, skip bins, combustible or hazardous materials, electrical or gas issues, access to underside of building)?',
      reference: 'netball-change-rooms-risks',
      component: 'Compliance',
    },
    {
      parent_id: '8b9c224c-7860-4df6-9d52-6a28e885b78d',
      text: 'Is there any issues with water/stormwater systems (Hot water systems, blocked drains/gutters, poor plumbing maintenance, overhanging trees)?',
      reference: 'netball-change-rooms-water-systems',
      component: 'Compliance',
    },
    {
      id: 'f3e47f73-dd44-4ab9-bb58-d3e1c2409560',
      props: { text: 'Kitchen/Cafe/Canteen Area' },
      component: 'FormSection',
    },
    {
      parent_id: 'f3e47f73-dd44-4ab9-bb58-d3e1c2409560',
      text: 'Is there any issues with water/stormwater systems (Hot water systems, blocked drains/gutters, poor plumbing maintenance)?',
      reference: 'kitchen-cafe-water-systems',
      component: 'Compliance',
    },
    {
      parent_id: 'f3e47f73-dd44-4ab9-bb58-d3e1c2409560',
      text: 'Is there any obvious property defects/hazards (slip or trip hazards, cracking, severe corrosion, breaks)?',
      reference: 'kitchen-cafe-water-defects',
      component: 'Compliance',
    },
    {
      parent_id: 'f3e47f73-dd44-4ab9-bb58-d3e1c2409560',
      text: 'Is the kitchen and storage area free from evidence of pests?',
      reference: 'kitchen-cafe-water-pests',
      component: 'Compliance',
    },
    {
      parent_id: 'f3e47f73-dd44-4ab9-bb58-d3e1c2409560',
      text: 'Is the kitchen area clean, neat and tidy?',
      reference: 'kitchen-cafe-water-clean',
      component: 'Compliance',
    },
    {
      parent_id: 'f3e47f73-dd44-4ab9-bb58-d3e1c2409560',
      text: 'Is the food registration certificate current and displayed appropriately?',
      reference: 'kitchen-cafe-water-certificate',
      component: 'Compliance',
    },
    {
      parent_id: 'f3e47f73-dd44-4ab9-bb58-d3e1c2409560',
      text: 'Is there any fire or arson risks (bins, combustible or hazardous chemicals/materials, electrical or gas issues) & have items been tested and tagged?',
      reference: 'kitchen-cafe-water-risks',
      component: 'Compliance',
    },
    {
      id: '25041b39-a6c5-484b-b92c-8fc7ac3aa5f6',
      props: { text: 'Reserve amenities' },
      component: 'FormSection',
    },
    {
      parent_id: '25041b39-a6c5-484b-b92c-8fc7ac3aa5f6',
      text: 'Are both change room areas and amenities clean, neat and tidy and free of rubbish?',
      reference: 'reserve-change-room-clean',
      component: 'Compliance',
    },
    {
      parent_id: '25041b39-a6c5-484b-b92c-8fc7ac3aa5f6',
      text: 'Is security measures adequate (lighting,visible portable equipment, vandalism)?',
      reference: 'reserve-change-room-security',
      component: 'Compliance',
    },
    {
      parent_id: '25041b39-a6c5-484b-b92c-8fc7ac3aa5f6',
      text: 'Is there any fire or arson risks (bins, combustible or hazardous materials)?',
      reference: 'reserve-change-room-risks',
      component: 'Compliance',
    },
    {
      parent_id: '25041b39-a6c5-484b-b92c-8fc7ac3aa5f6',
      text: 'Is there any obvious property defects/hazards (slip or trip hazards, cracking, severe corrosion, breaks)?',
      reference: 'reserve-change-room-defects',
      component: 'Compliance',
    },
    {
      id: 'e4a31c77-53a3-4187-b561-24a63d7b80ab',
      props: { text: 'Time Keeper/Scoreboard User Room' },
      component: 'FormSection',
    },
    {
      parent_id: 'e4a31c77-53a3-4187-b561-24a63d7b80ab',
      text: 'Is the area clean, neat and tidy and free of rubbish?',
      reference: 'scoreboard-room-clean',
      component: 'Compliance',
    },
    {
      parent_id: 'e4a31c77-53a3-4187-b561-24a63d7b80ab',
      text: 'Is the area locked and secure at time of inspection?',
      reference: 'scoreboard-room-secure',
      component: 'Compliance',
    },
    {
      parent_id: 'e4a31c77-53a3-4187-b561-24a63d7b80ab',
      text: 'Is there any obvious property defects/hazards (slip or trip hazards, cracking, severe corrosion, breaks)?',
      reference: 'scoreboard-room-defects',
      component: 'Compliance',
    },
    {
      id: '6979cc76-78f6-4e2d-914d-956af7ea8f6b',
      props: { text: 'Signage' },
      component: 'FormSection',
    },
    {
      parent_id: '6979cc76-78f6-4e2d-914d-956af7ea8f6b',
      text: 'Is warning and safety signage installed where necessary and well maintained e.g rules and conditions of use, disclaimers, emergency contact and location, warnings of inherent danger?',
      reference: 'signage-installed',
      component: 'Compliance',
    },
    {
      parent_id: '6979cc76-78f6-4e2d-914d-956af7ea8f6b',
      text: 'Is access and disabled signage installed where appropriate and well maintained e.g no entry, disabled access?',
      reference: 'signage-disabled',
      component: 'Compliance',
    },
    {
      parent_id: '6979cc76-78f6-4e2d-914d-956af7ea8f6b',
      text: 'All other relevant signage installed where required and in good condition e.g playground, tree or water risk, HAZCHEM?',
      reference: 'signage-other',
      component: 'Compliance',
    },
  ],
}

export default form
